name: 'Update Uclusion'
description: 'Update Uclusion job from push'

inputs:
  secret_key_id:
    description: 'Uclusion secret key id'
    required: true
  secret_key:
    description: 'Uclusion secret key'
    required: true
  workspace_id:
    description: 'Uclusion workspace id'
    required: true
  github-event-message:
    description: 'The push message with Uclusion job code'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.secret_key_id }}
    - ${{ inputs.secret_key }}
    - ${{ inputs.workspace_id }}
    - ${{ inputs.github-event-message }}
